type testEntry = {
  id: number;
  title: string;
  timestamp: Date;
  paragraphs: string[];
};

export const testEntries: testEntry[] = [
  {
    id: 1,
    title: "You",
    paragraphs: [
      "I walked along a path and ran into You.",
      "I looked at You and you at Me,",
      "In an instant we knew that We were We.",
      "",
      "It has been said that in other worlds beyond this,",
      "Different versions of You live unique lives,",
      "Playing unique roles, the same person but different.",
      "",
      `I asked You, "What was your life like?`,
      "What was different? What was the same?",
      "What was your family like? What role did you play?",
      "What was your life’s work? What skills had you learned?",
      `What would you ask yourself if yourself answered in return?"`,
      "",
      `"Did you have moments of joy? Did you have moments of sorrow?`,
      "What had you learned through life? What was important to you?",
      "What were your struggles? Did you have any regrets?",
      "What helps did you need? Had anyone answered your requests?",
      "Why do you think we are? What do you think is our purpose?",
      `Why are you? And why are we?"`,
      "",
      "You sat and pondered for a moment, then shared with me your joys,",
      "Your triumphs, your fears, your hopes, your tears, your pain, your love",
      "Your life, your knowledge, and indeed you shared with me",
      "What I would see from another perspective.",
      "",
      "I also shared my fears and hopes and dreams, ",
      "My joys, my sorrows, my achievements, my struggles,",
      "And it was in that moment when the realization struck",
      "About what the wise one once said",
      `"Do unto others as you would have done unto You."`,
      "I am You, and You are Me, and We are We.",
      "",
      "You saw things differently, but you confirmed we are the same",
      "You showed me that we are truly connected though living different lives",
      "And beyond all, you showed that we need not seek to travel vast distances",
      "To other worlds to see how we live in other lives, we need not travel so far",
      "To see that We are One, no matter who, what, or when we are",
      "When we see things from another’s eyes.",
    ],
    timestamp: new Date("7 August 2024"), //"7 August 2024",
  },
  {
    id: 2,
    title: "The Meeting",
    timestamp: new Date("25 January 2025"),
    paragraphs: [
      "For as long as I can reckon, you have been there",
      "",
      "Watching, waiting, observing.",
      "",
      "I stand looking down, to see your work. And I wonder why.",
      "Who are you? What are you? Why are you?",
      "",
      "It is said you meet all, and all shall know you. You have set a meeting with me, but have yet to let me know when.",
      "",
      "Surprise, anxiety, dread.",
      "",
      "Will it be a frightful pain? Will it be as though meeting a long lost friend, bringing to a place of peace?",
      "",
      "Joy, relief, rest.",
      "",
      "I see the works of your hands, and I am left wondering. How can this paradox be?",
      "",
      "Confusion, grief, pondering.",
      "",
      "This era of my life, where others cancel, has left me wondering. Should I ask to reschedule, to make sooner our meeting?",
      "",
      "Alone, afraid, with no one else to meet?",
      "",
      "Perhaps I should wait to meet you, only you know when it is time. It is a puzzle, great pain yet great relief you bring.",
      "",
      "Good yet evil, virtue yet vice, light yet darkness.",
      "",
      "But I’ve seen you lurking in the shadows, in moments so painful. Yet you are not menacing, you seem curious to meet.",
      "",
      "Powerful, omnipresent, flirtatious.",
      "",
      "One day, when you creep out from the shadows, I hope to know you well. And when I know you well, I hope our meeting is a good one.",
      "",
      "Quiet, humble, peaceful.",
    ],
  },
];
